name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Universal_Robots_ROS2_Driver/ur_robot_driver/resources/ursim_driver/driver/Dockerfile --build-arg ROS2_DISTRO=humble BUILD_MOVEIT2=1 --tag my-image-name:$(date +%s)
